### ISSUE TITLE
expo 47 compatible ?

### ISSUE THREAD

**Issue by igorcesarcode** [maxkomarychev/react-native-ultimate-config#114]
Hello thank you so much for the amazing tool

Does this library support expo?

when i give an npx create-expo-app and configure the library it always has several errors.

Is there a possibility to configure it along with the expo?

PS: Sorry for my English I'm not native

**Comment by maxkomarychev** [comment]
thanks for trying my lib! I have no experience with expo. it would help me understand the problem(s) if you could create an example of what and how breaks in a separate repository in a project from scratch. thanks!

**Comment by igorcesarcode** [comment]
@maxkomarychev Thanks a lot for the answer, however after some testing I found that the pre build exposition flow was enough for me.
