### ISSUE TITLE
Gradle 8 support

### ISSUE THREAD

**Issue by RayKay91** [maxkomarychev/react-native-ultimate-config#135]
As a developer I want to be able to use React Native Ultimate Config on Gradle version 8 which is the version used by React Native 0.72 up.

**Comment by vagnerlandio** [comment]
Hi,

I created a pull-request (https://github.com/maxkomarychev/react-native-ultimate-config/pull/136) that fix this.

Before the merge is done, can you test using the following [patch-package](https://www.npmjs.com/package/patch-package)?
`react-native-ultimate-config+6.0.0.patch`
```diff
diff --git a/node_modules/react-native-ultimate-config/android/build.gradle b/node_modules/react-native-ultimate-config/android/build.gradle
index de3e818..8b03219 100644
--- a/node_modules/react-native-ultimate-config/android/build.gradle
+++ b/node_modules/react-native-ultimate-config/android/build.gradle
@@ -114,7 +114,7 @@ if (isNewArchitectureEnabled()) {
 
 afterEvaluate { project ->
   task androidSourcesJar(type: Jar) {
-    classifier = 'sources'
+    archiveClassifier = 'sources'
     from android.sourceSets.main.java.srcDirs
     include '**/*.java'
   }
```

**Comment by RayKay91** [comment]
Thanks will have a check! 😄

**Comment by RayKay91** [comment]
Looks like it works! I've gotten further than before but am facing some issues with duplicate Kotlin classes which I don't believe are related to RNUC. Many thanks!

**Comment by maxkomarychev** [comment]
Version 6.0.1. has been published.
