### ISSUE TITLE
Null is not an object in iOS

### ISSUE THREAD

**Issue by ottodriver** [maxkomarychev/react-native-ultimate-config#14]
Hi and thanks for the good work.
I'm unable to get it working on iOS, is working fine on Android.
I've followed all the steps but whatever I try I get null is not an object each time I need access to configuration variable.

Do you've any idea/trick to try?
Best,
Leo

`null is not an object (evaluating '_env.default.API_BASE_URL')

create
    Api.js:39:30
<unknown>
    index.js:39:64
loadModuleImplementation
    require.js:303:6
<unknown>
    index.js:4
loadModuleImplementation
    require.js:303:6
<unknown>
    App.js:6
loadModuleImplementation
    require.js:303:6
<unknown>
    index.js:8
loadModuleImplementation
    require.js:303:6
guardedLoadModule
    require.js:195:45
`

**Comment by maxkomarychev** [comment]
@ottodriver hey, I'm sorry you have troubles with my library. Could you please provide more information? what is the version of your react-native? did you set up your project via quickstart guide? have you used any tricks from cookbook? It's best if you can provide a reproducible demo project which shows your problem. There's too little information available in your report to begin any troubleshooting.

**Comment by ottodriver** [comment]
Hi Max,
Sorry, I'm new to react-native, in fact I'm only building the multi
environment thing.
Finally I went back to react-native-config and get it working so you can
close this.
Thank you very much for your help.
Best,
Leo
