### ISSUE TITLE
Multiple env files possible?

### ISSUE THREAD

**Issue by joeldebont** [maxkomarychev/react-native-ultimate-config#140]
Hello,

I'm working on a white-label react native app where I have an env file per app version so each version has its own variable values. Now I also have variables that are needed in all app versions so I would like to have a general env file to store them in so I don't have to put those variables in all the other env files.

Is it possible to have multiple env files that are combined in a single config when running yarn rnuc?

I could'nt find it in the docs, but maybe I have missed it.

Cheers!

**Comment by maxkomarychev** [comment]
Hi @joeldebont, thanks for using the library!

Inheritance or merging from multiple env files is not supported directly. However you could achieve this behavior using `on_env` hook and override / enrich original env data with shared values. Please refer to cookbook for more details: https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/docs/cookbook.md
