### ISSUE TITLE
working with android release variant

### ISSUE THREAD

**Issue by sdenaci** [maxkomarychev/react-native-ultimate-config#17]
Hi! I love your library so much and we are so excited to incorporate it into our app. It will really solve a lot of our problems. 
Everything is working great for us on iOS, and in android debug variant. However, when we go to build in release variant, app, immediately crashes, with this as a typical kind of error
`null is not an object (evaluating 'f.default.KEY')`

Is there some special step we have to take to get the library to work in release variant?

Thanks so much for your time and all the work you have put into this library!

**Comment by sdenaci** [comment]
update: it is because we enable proguard. could you advise what to add to the progaurd rules file? thank you so much

**Comment by igorrfc** [comment]
I'm facing the exact same problem

**Comment by sdenaci** [comment]
I have arrived at a solution that works for me: 
In my proguard-rules.pro file
I have added

-keepclassmembers class [GOOGLE_APPLICATION_ID]BuildConfig {
    public static <fields>;
}

where GOOGLE_APPLICATION_ID is my actual google application id

**Comment by sdenaci** [comment]
I have added a quick pr to address this issue in docs in case it is helpful. Thank you so much agin for your wonderful library! :)

**Comment by sdenaci** [comment]
@igorrfc the <fields> was not showing up initially in my comment because I did not correctly use markdown. now it is showing up correctly. tagging you so I don't waste your time. :)

**Comment by igorrfc** [comment]
Thanks a lot for ur help @sdenaci! I'll try it out.

**Comment by maxkomarychev** [comment]
@sdenaci wow, thank you for this! I've got couple of questions in pr, other than that - looks great!

**Comment by maxkomarychev** [comment]
closed by https://github.com/maxkomarychev/react-native-ultimate-config/pull/18

**Comment by to-dy** [comment]
@maxkomarychev  @sdenaci 
Please how do I configure environments for different build variants.. cookbook only specifies for flavours.
Before switching to this library I use:
```
project.ext.envConfigFiles = [
    debug: ".env.dev.yaml",
    release: ".env.prod.yaml",
    devrelease: ".env.dev.yaml",
]
```

**Comment by maxkomarychev** [comment]
@to-dy `react-native-ultimate-config` does not currently allow binding configs to build variants but only to flavors.

This feature sounds interesting although I don't fully follow all edge cases, would you mind opening new issue with feature request explaining use cases for this feature, so we can discuss? thanks.
