### ISSUE TITLE
Url params encode

### ISSUE THREAD

**Issue by tr3v3r** [maxkomarychev/react-native-ultimate-config#2]
Hello! First of all, I'd like to say that I really appreciate you for such a great library!

Unfortunately, I've realized that there is some issue with string encoding. 

After run `yarn rnuc .env` url params like `app?=` was transformed into `?app&#x3D`. 

## Steps:
`yarn run .env`

## Actual result
`TEST=url?app=` --- > `TEST=url?app&#x3D`

## Expected result
`TEST=url?app=` --- > `TEST=url?app=`

Thank you!

**Comment by tr3v3r** [comment]
By the way `dotenv` itself parses as expected
[sanbox](https://codesandbox.io/s/nice-pond-jo7et?file=/src/App.js) (see console logs)

**Comment by maxkomarychev** [comment]
thank you for a good bug report!

it looks like handlebars by default url-escaping variables. the fix is on the way :) stay tuned.

**Comment by maxkomarychev** [comment]
@tr3v3r I have fixed this in version v1.2.3: https://github.com/maxkomarychev/react-native-ultimate-config/compare/v1.2.2...v1.2.3 please try it out :) thanks!

**Comment by maxkomarychev** [comment]
feel free to reopen if it still exists
