### ISSUE TITLE
'config' is null on Android

### ISSUE THREAD

**Issue by tr3v3r** [maxkomarychev/react-native-ultimate-config#39]
# Describe the bug

Application on Android crashes while running.
Everything is ok on iOS

# Steps to Reproduce

1) yarn rnuc .env
2) react-native run-android

The bundle is built but the app crashes with error:

TypeError: Cannot read property 'NATIVE_CLIENT_URL' of null, js engine: hermes

Code:

```
import config from 'react-native-ultimate-config';

new NativeApiService(config.NATIVE_CLIENT_URL);
```

# Expected behavior

The app shouldn't crash.

# Stacktraces, logs, screenshots

<img width="200" src='https://user-images.githubusercontent.com/23724142/91547917-48a82280-e92d-11ea-9b9c-e3f0a20076a1.png'>

# Environment

## Integration option

- [x] I am using `rnuc` CLI to inject environment (default integration option
      from [quickstart guide](../../docs/quickstart.md))
- [ ] I am using scheme/flavor based integration (experimental integration
      option from cookbook:
      [scheme](../../docs/cookbook.md#using-multiple-schemes-ios),
      [flavors](../../docs/cookbook.md#using-multiple-flavors-android))
- [ ] I am using `react-native-ultimate-config` within monorepo managed with
      Lerna or Yarn Workspaces [Monorepo support](../../docs/api.md#advanced-options-for-monorepo)

## Env file

- [x] I am using dotenv file as a source for variables
- [ ] I am using YAML file as a source for variables

### Example of env file that is causing problems

```
ENVIRONMENT=development

NATIVE_CLIENT_URL=http://my-url
```

## OS

- [ ] ios
- [x] android

## Packages

- version of `react-native`: 0.63.1
- version of `react-native-ultimate-config`: 3.2.3
Run `react-native info` and post below:

```
System:
    OS: macOS 10.15
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.72 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-22 | Google APIs Intel x86 Atom_64, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.1 => 0.63.1 
  npmGlobalPackages:
    *react-native*: Not Found
```

# Additional context

**Comment by maxkomarychev** [comment]
hi @tr3v3r , thanks for the report
could you please provide a bit more context about your issue, more specifically:

1. I see you're using react-native 0.63 with hermes. I haven't been able yet to try this setup. Did it work for you in lower versions of react-native and/or without hermes?
2. could you please check if you can access this variable in java code as explained here in this doc https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/docs/api.md#java ?

Thanks!

**Comment by tr3v3r** [comment]
Hi @maxkomarychev, thanks for your reply! 
My fault...
I've just realized that I missed step **6** from [this](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/docs/quickstart.md) tutorial. I thought that this step is optional and needed just if you need access to env variables on the native side...

Everything is OK now. Thanks
