### ISSUE TITLE
Confused about rnuc vs. react-native-ultimate-config

### ISSUE THREAD

**Issue by ahartzog** [maxkomarychev/react-native-ultimate-config#4]
Hey, I have it working but just curious.

I'm using NPM, not yarn, so I have it installed via `npm -E react-native-ultimate-config`

Then in order to actually run the scripts I'm currently doing `npx yarn rnuc './.deploy/.stage.env'`

What is "rnuc" specifically? Is that a separate package? 

If that's obvious to people who use yarn all the time, it might be worth explaining in the docs.

**Comment by maxkomarychev** [comment]
I guess I'm just used to yarn and didn't think about such difference.

`rnuc` is an executable script distributed together with the package, when you install a library both npm and yarn create symlinks to binary files in `node_modules/.bin/..`

so for yarn it's enough to do `yarn <bin file>` but for npm this will be `$(npm bin)/<bin file`

in our case it will be `$(npm bin)/rnuc`

I can't give any better recipe for npm other than adding script in your `package.json`:

```
"rnuc": "$(npm bin)/rnuc"
```
and then you can execute it with npm like


```
npm run rnuc <env file>
```

**Comment by maxkomarychev** [comment]
I'll update docs soon, thanks feedback!

**Comment by ahartzog** [comment]
Awesome! I'll implement that NPM recipe. Thank you!

Thanks for this lib btw.

**Comment by maxkomarychev** [comment]
@ahartzog I have updated docs with `npm` variants of every command, please check it out.

thank you!

**Comment by ahartzog** [comment]
Looks great, thanks!

**Comment by nikola1970** [comment]
> I guess I'm just used to yarn and didn't think about such difference.
> 
> `rnuc` is an executable script distributed together with the package, when you install a library both npm and yarn create symlinks to binary files in `node_modules/.bin/..`
> 
> so for yarn it's enough to do `yarn <bin file>` but for npm this will be `$(npm bin)/<bin file>`
> 
> in our case it will be `$(npm bin)/rnuc`
> 
> I can't give any better recipe for npm other than adding script in your `package.json`:
> 
> ```
> "rnuc": "$(npm bin)/rnuc"
> ```
> 
> and then you can execute it with npm like
> 
> ```
> npm run rnuc <env file>
> ```

what would be this command on windows since I get the error "'$' is not recognized as an internal or external command,
operable program or batch file."? Thanks!

**Comment by maxkomarychev** [comment]
@nikola1970 I don't have access to windows to try this out. I would recommend asking the question in stackoverflow since it's not specific to this library and more about using shell on windows.
