### ISSUE TITLE
Injecting values in main/assests/appcenter-config.json on Android

### ISSUE THREAD

**Issue by vladamx** [maxkomarychev/react-native-ultimate-config#41]
Is it possible to inject values from env file in arbitrary files like main/assests/appcenter-config.json on Android?

Thanks.

**Comment by maxkomarychev** [comment]
Hi, 

it is not possible to inject values into such files by default but you can use hooks and copy prepared plist files from to your project. An example of how hooks can be used is located [here](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/docs/cookbook.md#generate-fastlane-dotenv).
