### ISSUE TITLE
Injecting values in arbitrary plist files on IOS

### ISSUE THREAD

**Issue by vladamx** [maxkomarychev/react-native-ultimate-config#42]
Is it possible to inject values from env file in arbitrary plist files in root? 
For example AppCenter-Config.plist

Thanks.

**Comment by maxkomarychev** [comment]
Hi, 

it is not possible to inject values into such files using builtin capabilities of xcode (it doesn't interpolate values in plist files other that info.plist) however you can use [hooks capability](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/docs/api.md#hooks) and copy prepared plist files from to your project. An example of how hooks can be used is located [here](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/docs/cookbook.md#generate-fastlane-dotenv)

**Comment by vladamx** [comment]
Thanks @maxkomarychev
