### ISSUE TITLE
Replace values in string.xml

### ISSUE THREAD

**Issue by vieraleonel** [maxkomarychev/react-native-ultimate-config#46]
Is it posible to use .yaml values in string.xml.

For example:

- env.yaml
```bash
CODEPUSH_KEY:
  android: "myAndroidKey"
  ios: "myiOSKey"
```

- android/app/src/main/res/values/strings.xml
```xml
<resources>
    <string name="app_name">PanalDev</string>
    <string moduleConfig="true" name="CodePushDeploymentKey">${CODEPUSH_KEY}</string>
</resources>
```

I've tried it without success but maybe there is a trick to make it work

Thanks!

Great work

**Comment by maxkomarychev** [comment]
hi @vieraleonel ,

Quick research on my side didn't yield any results on whether there is a way to reference to one strings value in another. And I'm not sure if there is something I can do on side of the library. Although I'm not an android expert by all means.

At this point I can recommend you to try [hooks](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/docs/api.md#hooks) functionality of my library and generate necessary xml yourself.

very-very rough example:


```js
module.exports = {
  on_env: async function (env) {
    fs.writeFileSync(
      'android/app/src/main/res/values/strings.xml',
      `<resources>
    <string name="app_name">PanalDev</string>
    <string moduleConfig="true" name="CodePushDeploymentKey">${env['CODEPUSH_KEY']}</string>
</resources>`,
    );
  },
};

```

more references:

1. [cookbook section](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/docs/cookbook.md#generate-fastlane-dotenv)
2. [similar issue](https://github.com/maxkomarychev/react-native-ultimate-config/issues/30)


hope this helps

**Comment by maxkomarychev** [comment]
Alternatively: according to the [documentation](https://github.com/microsoft/react-native-code-push/blob/c0cc20e95f29a099b0e95d915e0a8a46cefd49db/docs/api-js.md#CodePushOptions) of codepush it is possible to specify codepush key at runtime

**Comment by vieraleonel** [comment]
Hi @maxkomarychev, sorry for the late feedback. I was caught up with some deadlines.

I've solved it first with changing the key at runtime but I was able to generate `strings.xml` with your example, so now is a super clean solution.

Also the same solution apply to `colors.xml` and other files so its super useful.

Thank you very much. Excellent package.
