### ISSUE TITLE
How is it different from react-native-config? 

### ISSUE THREAD

**Issue by jay-jlm** [maxkomarychev/react-native-ultimate-config#47]
Congratz on your project.

I think it would save newcomers some precious research time if you could include some information in the README on how it differs from `luggit/react-native-config` and the potential benefits of switching over for projects that already use that other solution.

**Comment by maxkomarychev** [comment]
@jay-jlm I put some comparison here https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/docs/alternatives.md (also linked from README).

Please feel free to suggest if more that page needs to contain more information, closing this meanwhile.

Thanks!
