### ISSUE TITLE
Error while running in AppCenter

### ISSUE THREAD

**Issue by coffteam2020** [maxkomarychev/react-native-ultimate-config#48]
* Where:
Script '/Users/runner/work/1/s/node_modules/react-native-ultimate-config/android/rnuc.gradle' line: 17

* What went wrong:
A problem occurred evaluating script.
> yaml file at path /Users/runner/work/1/s/node_modules/react-native-ultimate-config/android/rnuc.yaml does not exist

I think it could not find any yaml file in root, instead of android folder. How can I resolve this? @maxkomarychev @sdenaci @irohitb, thanks for incredible lib, hope you give me a solution to fix this

**Comment by maxkomarychev** [comment]
@coffteam2020 I'd need more context to help wit this. Can you pease reopen this issue using "bug" template and answer all relevant questions?

From what I see here I can only suspect you have not called `yarn rnuc ...yaml` before trying to compile the app.

**Comment by coffteam2020** [comment]
We use env files to use multiple flavors. Not yaml file.
For rnuc, we use: npm run rnuc ../env.

**Comment by maxkomarychev** [comment]
1. is this reproducible locally?
2. what is the version of library are you using?
3. are you using flavor-based integration or running rnuc manually before the build?
4. what is the command that appcenter perform? please provide full details of how this is set up there

I cant help if you dont share all possible details or provide a reproducible project.
The fact it happens only kn CI hints there is something happening differently on CI. and your computer.

Max.

**Comment by isilher** [comment]
Personally when I had this it was because one of the steps in AppCenter would clean our working directory. I added the `rnuc` command to the end of our `appcenter-post-clone.sh` file to ensure the config files are set before building.

**Comment by maxkomarychev** [comment]
@isilher would you mind opening a pull request and adding this know-how in cookbook?

**Comment by isilher** [comment]
Sure! Expect one in the coming week.

**Comment by maxkomarychev** [comment]
hey @coffteam2020 

can you please try to apply a fix suggested by @isilher in [troubleshooting guide](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/docs/troubleshooting.md#-example-building-the-project-on-appcenter) ?
