### ISSUE TITLE
v3.0.0 - v3.3.1 Android cannot load url in webview

### ISSUE THREAD

**Issue by hanifmhd** [maxkomarychev/react-native-ultimate-config#49]
# Describe the bug
I just upgraded lib to the latest version, `v3.3.1`. Then i run `yarn rnuc .env`, but it cannot load webview url, always return error. I try to install all lib version, only `v2.2.0` that can run url in webview.

# Steps to Reproduce

1. create webview react native project
2. create env file with values, for example: `ANDROID_URL=https://google.com`
3. run `yarn rnuc .env`

# Expected behavior

load that url in webview

# Stacktraces, logs, screenshots
`error [TypeError: Network request failed]`
<img width="697" alt="Screen Shot 2021-03-23 at 11 42 26" src="https://user-images.githubusercontent.com/15220788/112094044-19107e80-8bcd-11eb-90b3-ccf2067befe3.png">

# Environment

## Integration option

- [x] I am using `rnuc` CLI to inject environment (default integration option
      from [quickstart guide](../../docs/quickstart.md))
- [ ] I am using scheme/flavor based integration (experimental integration
      option from cookbook:
      [scheme](../../docs/cookbook.md#using-multiple-schemes-ios),
      [flavors](../../docs/cookbook.md#using-multiple-flavors-android))
- [ ] I am using `react-native-ultimate-config` within monorepo managed with
      Lerna or Yarn Workspaces [Monorepo support](../../docs/api.md#advanced-options-for-monorepo)

## Env file

- [x] I am using dotenv file as a source for variables
- [ ] I am using YAML file as a source for variables

### Example of env file that is causing problems

```
ANDROID_URL=https://google.com
```

## OS

- [ ] ios -> working well
- [x] android

## Packages

- version of `react-native`: 0.62.2
- version of `react-native-ultimate-config`: ^3.3.1

Run `react-native info` and post below:

```
System:
    OS: macOS 11.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 41.53 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.6.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

# Additional context

**Comment by maxkomarychev** [comment]
hi @hanifmhd ,

I am sorry you are having troubles but I can not reproduce this problem with fresh react-native project.

Have you followed migration [guide for version 3](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/CHANGELOG.md#300-2020-04-27) ? 
I would also recommend going over [the quickstart guide](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/docs/quickstart.md) in order to make sure your integration is correct.
Given available information I would speculate you are missing `setBuildConfig` in your `MainApplication.java`.

If the error still exists I would ask you to share a demo project which demostrates this problem.

thanks.

**Comment by hanifmhd** [comment]
> hi @hanifmhd ,
> 
> I am sorry you are having troubles but I can not reproduce this problem with fresh react-native project.
> 
> Have you followed migration [guide for version 3](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/CHANGELOG.md#300-2020-04-27) ?
> I would also recommend going over [the quickstart guide](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/docs/quickstart.md) in order to make sure your integration is correct.
> Given available information I would speculate you are missing `setBuildConfig` in your `MainApplication.java`.
> 
> If the error still exists I would ask you to share a demo project which demostrates this problem.
> 
> thanks.

hi @maxkomarychev ,

Thank you so much for your guidance, i just read the changelog and there is additional configuration for v3 above.
I missed the quickstart guide about `setBuildConfig`.

Right now, it's working well on Android and iOS, appreciate your help.
Thank you.
