### ISSUE TITLE
Jest: Mock the library react-native-ultimate-config

### ISSUE THREAD

**Issue by aymkin** [maxkomarychev/react-native-ultimate-config#55]
One of the files has (translation setup) imports the RNUC. And the selection of the right translations is heavily relies on .env variables. During the runtime, it resolves properly:

```javascript
import config from 'react-native-ultimate-config';

console.log('--- config --- ', config);

// output
// --- config ---  {
// APP_NAME: "fooBar",
// BUNDLE_ID: "com.foo.bar
// ....
// }
```

But if I run the test
```bash
yarn jest app/component/Component.test.tsx
```
the output is
```javascript
--- config ---  {}
```

That means I need to mock the library somehow, and I did not found the proper instructions in [README](https://github.com/maxkomarychev/react-native-ultimate-config#readme)

Please guide me on how to implement that.

Thank you a lot

@isilher @maxkomarychev

**Comment by isilher** [comment]
Hi @aymkin! For jest, simply treat it as a native dependency and mock it. For example:

``` js
jest.doMock('react-native-ultimate-config', () => {
  return {
    APP_NAME: "fooBar",
    BUNDLE_ID: "com.foo.bar",
  }
})
```

**Comment by maxkomarychev** [comment]
Hi @aymkin ,

there's nothing special about mocking this library. It can be mocked with [jets's module mocks](https://jestjs.io/docs/mock-functions#mocking-modules). Something as simple as:

```js
jest.mock('react-native-ultimate-config', () => ({
    APP_NAME: "fooBar",
    BUNDLE_ID: "com.foo.bar",
}))
```

if you got more troubles with these - please consider sharing a reproducible example. thank you.

**Comment by aymkin** [comment]
What I actually did
* in the root directory in the folder `__mocks__` (sibling to `node_modules`) I created a file as a library name, so I got `__mocks__/react-native-ultimate-config.ts`
* in that file I put the following content 
```javascript
import { ConfigVariables } from 'react-native-ultimate-config';

const ReactNativeUltimateConfig: ConfigVariables = {
  APP_NAME: 'string',
  APP_VERSION: 'string',
  BUNDLE_ID: 'string',
  WHITE_LABEL_ID: 'string',
  API_ENV: 'string',
  BRAND_ID: 'string',
  BRAND_DATA_BRAND: 'string',
  BRAND_URL: 'string',
  BRAND_EMAIL: 'string',
  BRAND_PHONE: 'string',
  PUSHER_KEY: 'string',
  APPLE_ID: 'string',
};
```

That is it, PROFIT!

**Comment by maxkomarychev** [comment]
To be honest I'm slightly confused with how this can work at all.

Seems like some typescript definitions are not 100% accurate. 

There is no exported variable `ConfigVariables` - there is only one `default` export: https://github.com/maxkomarychev/react-native-ultimate-config/blob/51e133ee0f45f157fe82475a57c9ff0b7dd79fac/index.js#L1-L6

and the default export should be mocked, not `ConfigVariables`. 
that said I have never tried to mock it myself, I need to try it.

**Comment by aymkin** [comment]
There are `ConfigVaribles` in `node_modules/react-native-ultimate-config/index.d.ts`

**Comment by maxkomarychev** [comment]
yes, that's the problem - this *not a variable* that is exported. it's rather ephemeral variable which exists only in typescript but no in js

**Comment by maxkomarychev** [comment]
I added example of mock here https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/packages/example/__tests__/App-test.js
