### ISSUE TITLE
Module UltimateConfig required main queue setup warning

### ISSUE THREAD

**Issue by ahartzog** [maxkomarychev/react-native-ultimate-config#6]
![image](https://user-images.githubusercontent.com/9828263/79782990-f49d8980-830d-11ea-849a-61755d94504e.png)

Hey, I figured you've seen this before, it seems like all you need to do is drop in the 'requiredMainQueueSetup' somewhere? 

I'm not very familiar with native-side stuff or I'd throw up a PR for you lol. I can try if you want me too.

Figured it'd be nice to eliminate this warning every time and avoid a future bug.

**Comment by maxkomarychev** [comment]
@ahartzog fixed in [v2.0.1](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/CHANGELOG.md#201-2020-04-20) thanks for report! 👍

**Comment by ahartzog** [comment]
Awesome, thanks @maxkomarychev!
