### ISSUE TITLE
3.4.0 doesn't support React 17

### ISSUE THREAD

**Issue by bill-dai** [maxkomarychev/react-native-ultimate-config#71]
Upgraded to React Native 0.65.1 today and it requires React 17.0.2, but RNUC doesn't support it. 

Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.1" from react-native-ultimate-config@3.4.0
npm ERR! node_modules/react-native-ultimate-config
npm ERR!   react-native-ultimate-config@"*" from the root project

Should I use the -- force option to force the dependency conflict?

**Comment by maxkomarychev** [comment]
hi @bill-dai 

thank you for this report, I believe peer dependency of `react` has gotten here by a mistake - there is nothing in this library why you would need `react` for.. I'll issue a new version soon

**Comment by maxkomarychev** [comment]
please try version [3.4.1](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/packages/react-native-ultimate-config/CHANGELOG.md#341-2021-09-06)

feel free to reopen if this still happens

thanks for chosing `react-native-ultimate-config` :)
