### ISSUE TITLE
Values only accessable in debug mode (without flavors)????

### ISSUE THREAD

**Issue by zoobibackups** [maxkomarychev/react-native-ultimate-config#78]
My .env file
```
APPLICATION_ID=my_app_id_here
NAME=app_name_here
```

then i run this command:
`yarn rnuc .env`

Then in my react-native app i access the values as: 
```
import config from 'react-native-ultimate-config'

config.NAME // access it here
```

But these values are only accessable in debug mode

In release mode its undefined??????

**Comment by maxkomarychev** [comment]
hi @zoobibackups 

please provide more context and exact steps/commands on how do you run this in debug mode and in release.

thanks

**Comment by zoobibackups** [comment]
> how do you create release apk? do you do this locally or on some CI service? can you please provide reproducible example ?

Its working now, i don't know what was the issue but its working now. 
Thanks

**Comment by zjxdm** [comment]
Mine is the same as you, how to solve it ?

**Comment by rushant11** [comment]
> > how do you create release apk? do you do this locally or on some CI service? can you please provide reproducible example ?
> 
> Its working now, i don't know what was the issue but its working now. Thanks

I getting undefined values in both debug and release, follows the steps as you did.
