### ISSUE TITLE
initialize env from code ?

### ISSUE THREAD

**Issue by Afsarunnisa** [maxkomarychev/react-native-ultimate-config#92]
is there any way to initiate env file from code ? means we need to change env files based on user selection in testing.

**Comment by maxkomarychev** [comment]
This is not supported and will likely be not supported.

Core concept of this library is to propagate configurations from native side. Many of those settings are injected at build time and one can not change them from a built product. Doing this kind of a shortcut is not something I would want to support. Moreover - if a configuration is *ONLY* held within javascript then there is no need to employ special library :)

Thanks!
